### ISSUE TITLE
Dead links / Duke is lost

### ISSUE THREAD

**Issue by paulvi** [imifos/Java-Duke-AoI-Models#1]
http://kenai.com/projects/duke and http://duke.kenai.com are no longer available.

It is not possible/easy to find Duke

**Comment by paulvi** [comment]
OK, found at http://openjdk.java.net/projects/duke/

**Comment by imifos** [comment]
Yes, all this changed a bit in the meantime :) Thank you for the link!

**Comment by paulvi** [comment]
Could you update https://imifos.github.io/Java-Duke-AoI-Models/ or just README

**Comment by imifos** [comment]
Done! Thank you for pushing me for being lazy :)

**Comment by paulvi** [comment]
Just making world a little bit better
